#!/bin/bash
USER_INSTANCE=$(dirname $0)
INTERFACE=$(ip route get 8.8.8.8 | awk -- '{printf $5}') 
ACCOUNTS=`cat accounts.txt`  
if ! [ -d "./bin" ]; then
	echo "(!) This script requires libcathook.so!"
	exit
fi
echo "(!) Injecting cathook into sandboxed TF2"
firejail --join=b0 bash -c sudo ./attach