#!/bin/bash
$net=ip -br l | awk '$1 !~ "lo|vir|wl" { print $1}'
if ! [ -d "./user_instances" ]; then
	echo "(!) You need to run install first."
	exit
fi

echo "(!) Launching sandboxed steam"
firejail --dns=1.1.1.1 --noprofile --private=/home/qt/Desktop/github_lao/user_instances/b0 --name=b0 --env=PULSE_SERVER=unix:/tmp/pulse.sock --env=STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 --env=DISPLAY=:0.0 steam -noreactlogin -login

#todo: add a way to steam see TF2 installation
#echo "(!) Launching TF2"
#firejail --join=b0 bash -c cd ~/.local/share/Steam/steamapps/common/Team\ Fortress\ 2 && LD_LIBRARY_PATH="$(~/".local/share/Steam/ubuntu12_32/steam-runtime/run.sh" printenv LD_LIBRARY_PATH):./bin" STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 DISPLAY=:0.0 PULSE_SERVER="unix:/tmp/pulse.sock" ./hl2_linux -game tf -w 640 -h 480 -steam -secure -novid

echo "(-) cathook-sandbox has stopped."
