#!/bin/bash
USER_INSTANCE=$(dirname $0)
if ! [ -d "./user_instances" ]; then
	echo "(!) You need to run install first."
	exit
fi

echo "(!) Fixing NVIDIA crash"
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg

#todo: let user create more instance
echo "(!) Creating default instance"
cd $USER_INSTANCE/user_instances
mkdir b0
cd ..

echo "(!) Launching sandboxed steam"
firejail --dns=1.1.1.1 --noprofile --private=$USER_INSTANCE/user_instances/b0 --name=b0 --env=PULSE_SERVER=unix:/tmp/pulse.sock --env=STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 --env=DISPLAY=:0.0 steam -noreactlogin -login
0 --env=DISPLAY=:0.0 steam -noreactlogin -login #todo: let user specify login details from file.

#todo: add a way to steam see TF2
#echo "(!) Launching TF2"
#firejail --join=b0 bash -c cd ~/.local/share/Steam/steamapps/common/Team\ Fortress\ 2 && LD_LIBRARY_PATH="$(~/".local/share/Steam/ubuntu12_32/steam-runtime/run.sh" printenv LD_LIBRARY_PATH):./bin" STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 DISPLAY=:0.0 PULSE_SERVER="unix:/tmp/pulse.sock" ./hl2_linux -game tf -w 640 -h 480 -steam -secure -novid

echo "(-) cathook-sandbox has stopped."
