#!/bin/bash
USER_INSTANCE=$(dirname $0)
INTERFACE=$(ip route get 8.8.8.8 | awk -- '{printf $5}') 
ACCOUNTS=`cat accounts.txt`  
if ! [ -d "./user_instances" ]; then
	echo "(!) You need to run install first."
	exit
fi
sudo chmod 700 /opt/steamapps/common/Team\ Fortress\ 2/tf/glshaders.cfg
cd $USER_INSTANCE/user_instances
mkdir b0
cd ..
sudo $USER_INSTANCE/scripts/ns-inet 0
firejail --dns=1.1.1.1 --net=$INTERFACE --netns=catbotns0 --noprofile --private=$USER_INSTANCE/user_instances/b0 --name=b0 --env=PULSE_SERVER=unix:/tmp/pulse.sock --env=STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0 --env=DISPLAY=:0.0 steam -noreactlogin -login -slient -nominidumps -nobreakpad -no-browser